export { default as PageHeader } from '../Shared/pageHeader';
export { default as Banner } from './banner-section';
export { default as About } from './about-section';
export { default as NewIn } from './new-in-section';
export { default as ScrollProgressBar } from '../Shared/back-to-top-scroll-progress';
export { default as ProductDetails } from './product-details';
export { default as AllProductsMenu } from './all-products-Menu';
export { default as Pagination } from './pagination';
export { default as ProductCard } from './product-card';